//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rosu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Committee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Committee()
        {
            this.CommitteeMembers = new HashSet<CommitteeMember>();
            this.Programs = new HashSet<Program>();
        }
    
        public int commiteeID { get; set; }
        [Display(Name ="Committee Name")]
        public string committee_name { get; set; }
        [Display(Name = "Role")]
        public string job_description { get; set; }
        [Display(Name = "Leader")]
        public int committee_leader { get; set; }
        [Display(Name = "Member No.")]
        public int numberOfMembers { get; set; }
    
        public virtual Executive Executive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommitteeMember> CommitteeMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs { get; set; }
    }
}
