//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rosu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Stakeholder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stakeholder()
        {
            this.studentLeaders = new HashSet<studentLeader>();
        }
        [Display(Name = "Stakeholder ID")]
        public int stakeholderID { get; set; }

        [Display(Name = "Stakeholder's Name")]
        public string stakeholder_name { get; set; }
        [Display(Name = "Purpose of Engagement")]
        public string engagementPurpose { get; set; }
        [Display(Name = "Date of Engagement")]
        public Nullable<System.DateTime> dateEngaged { get; set; }
        [Display(Name = "Email")]
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentLeader> studentLeaders { get; set; }
    }
}
